// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateArtwork(ctx context.Context, arg CreateArtworkParams) (Artwork, error)
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	GetArtwork(ctx context.Context, id pgtype.UUID) (GetArtworkRow, error)
	GetArtworkRaw(ctx context.Context, id pgtype.UUID) (Artwork, error)
	GetArtworkWithImages(ctx context.Context, id pgtype.UUID) ([]GetArtworkWithImagesRow, error)
	ListArtworks(ctx context.Context) ([]ListArtworksRow, error)
	ListArtworksRaw(ctx context.Context) ([]Artwork, error)
}

var _ Querier = (*Queries)(nil)
